### ISSUE TITLE
Help me please

### ISSUE THREAD

**Issue by Lookman98** [gtteamamxx/Flutter-weather-app-apixu#1]
how to remove translation and why astro and upcoming day didnt work
thank you

**Comment by gtteamamxx** [comment]
Hello which translation do you want to remove?

At moment of the uploading project to github all featuers worked well.
Now I can't tell you why it doesn't work. 
maybe apixu changed API or model, or something and it crashes.

Feel free to make FIX

**Comment by Lookman98** [comment]
i want remove language translation

**Comment by gtteamamxx** [comment]
You have to then learn programming. I'm not gonna do that for you.
Translations are just on views.
![image](https://user-images.githubusercontent.com/10392319/62937116-f05abd00-bdcb-11e9-9a34-f15299c856c9.png)

**Comment by Lookman98** [comment]
no i mean the one with condition translation 
![Capture](https://user-images.githubusercontent.com/29520080/62937770-2a45b680-be00-11e9-8d31-0578c139fe3a.PNG)

**Comment by gtteamamxx** [comment]
To do that, change body of translator.translateConditionByCode
find that:
` String translatedCondition = translation.languages.firstWhere((language) => language.language == languageKey)?.dayText;`
and replace it to:
`String translatedCondition = translation?.dayText`;

then you gonna have all english translations

or, just add one if in proper place. It should work

`if(languageKey == "English") { translatedContiion = translation?.dayText)`

**Comment by Lookman98** [comment]
i try your solution and it doesnt work , because apixu dont have lang_name =  english 

This is my solution :
![Capture](https://user-images.githubusercontent.com/29520080/62940420-2321a700-be06-11e9-92e9-17b88755d124.PNG)

thank you for you help

**Comment by Lookman98** [comment]
or just  make translateConditionByCode (??,??){//leave it blank}

**Comment by gtteamamxx** [comment]
Nooo, it's stupid solution :D

**Comment by gtteamamxx** [comment]
Change it as i told you.
Here is structure of json file
http://www.apixu.com/doc/conditions.json

Look carefuly - there are english translations

**Comment by Lookman98** [comment]
yeah i also think it stupid solution xD
i cant find lang_name="English" but there is english translation as default it is english
![image](https://user-images.githubusercontent.com/29520080/62941833-911b9d80-be09-11e9-9386-b79b2e3bdd14.png)
![image](https://user-images.githubusercontent.com/29520080/62941967-db048380-be09-11e9-9bfe-335c5f8fc596.png)

**Comment by gtteamamxx** [comment]
Hmm, change dayText to Day 




Pobierz aplikację Outlook dla systemu Android







On Tue, Aug 13, 2019 at 2:36 PM +0200, "Lookman98" <notifications@github.com> wrote:












yeah i also it stupid solution xD

i cant find lang_name="English" but there is english translation as default it is english

**Comment by Lookman98** [comment]
okay sir thank you , its working :D

**Comment by Lookman98** [comment]
do you have any idea why this line return null value?

![image](https://user-images.githubusercontent.com/29520080/62989226-c52ea700-be79-11e9-8a55-6a66283dd1bc.png)
