### ISSUE TITLE
NoSuchMettodError:The getter 'forcastDays' was called on null

### ISSUE THREAD

**Issue by Lookman98** [gtteamamxx/Flutter-weather-app-apixu#2]
The forecast cant load , so i try find the cause, i commented the error_button and i got this error : 
"NoSuchMettodError:The getter 'forcastDays' was called on null"

where should i check to overcome this problem ? 
dashboard_forecast_page.dart

![image](https://user-images.githubusercontent.com/29520080/63002037-90d1df80-bea7-11e9-94c3-390800def00f.png)

Thank you

**Comment by gtteamamxx** [comment]
Hmm, as I Told you yesterday it looks like APIXU changed some API models or something and you have to customize it to new API model.
On my free time i will run this app and check what's going on.

**Comment by Lookman98** [comment]
what this line for?
  var days = viewModel.forecast.forecastDays;
is it to get the number of day?

**Comment by gtteamamxx** [comment]
I made a fix, now it all works:
![image](https://user-images.githubusercontent.com/10392319/63003506-949a3d80-be78-11e9-814c-20a9eacba9b6.png)

As I Thought the difference was with Type of data.
JSON was returning a type of double:
![image](https://user-images.githubusercontent.com/10392319/63003564-b3003900-be78-11e9-8f58-00e0a8dc79e8.png)

But in code was string.
![image](https://user-images.githubusercontent.com/10392319/63003575-b98eb080-be78-11e9-9b82-f8f34fd5ccc8.png)


Merge with master and all gonna work

**Comment by Lookman98** [comment]
so i need to change any related to uv to double right?

**Comment by gtteamamxx** [comment]
In   ForeCastDayModel change 
1.`String get uv` to `double get uv;`
2. in dashboard_day_detail_page.dart change in line 48 `percentage: double.parse(viewModel.dayInfo.day.uv),` to `percentage: viewModel.dayInfo.day.uv,`
and  54 `Text(viewModel.dayInfo.day.uv [...]` to `Text(viewModel.dayInfo.day.uv.toString() ....`

**Comment by gtteamamxx** [comment]
3. run in terminal: `flutter packages pub run build_runner build --delete-conflicting-outputs`
and all should works

**Comment by Lookman98** [comment]
owhh man i already change uv to double before i ask you 
3rd step very do the trick

thank youuuuu :D

**Comment by gtteamamxx** [comment]
No problem
